# Server port
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://danajakulathunga3_paf:pafD2003911d@notificationsrolemanage.mol1xjb.mongodb.net/NotificationsRoleManagementOAuth?appName=NotificationsRoleManagementOAuth&authSource=admin

# JWT Configuration
# Replace this with a strong 256-bit secret key in production
smartcampus.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
smartcampus.app.jwtExpirationMs=86400000

# Google OAuth2 Configuration
# Note: Provide your actual Client ID and Secret obtained from Google Cloud Console
spring.security.oauth2.client.registration.google.client-id=493767701720-0ocg62hstelp32gqp021u1vt6jaalhhg.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Frontend callback after successful OAuth2 authentication
app.oauth2.redirectUri=http://localhost:5173/oauth-success
